=== QuarkNet-HEP/e-Labs/template/resources/WEB-INF/classes/gvds-poolcfg-1.5.xsd
<?xml version="1.0" encoding="UTF-8"?><!-- edited with XMLSPY v5 rel. 3 U (http://www.xmlspy.com) by smarty (smarty) --><xs:schema xmlns="http://www.griphyn.org/chimera/GVDS-PoolConfig" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.griphyn.org/chimera/GVDS-PoolConfig" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.5">	<xs:simpleType name="ProfileNamespace">		<xs:annotation>			<xs:documentation>defines the legal namespaces of execution profiles.</xs:documentation>		</xs:annotation>		<xs:restriction base="xs:NMTOKEN">			<xs:enumeration value="vds"/>			<xs:enumeration value="condor"/>			<xs:enumeration value="dagman"/>			<xs:enumeration value="env"/>			<xs:enumeration value="hints"/>			<xs:enumeration value="globus"/>		</xs:restriction>	</xs:simpleType>	<xs:attributeGroup name="GlobusVersionInfo">		<xs:annotation>			<xs:documentation>A set of attributes to define a Globus version.</xs:documentation>		</xs:annotation>		<xs:attribute name="major" type="xs:positiveInteger" use="required"/>		<xs:attribute name="minor" type="xs:nonNegativeInteger" use="required"/>		<xs:attribute name="patch" type="xs:nonNegativeInteger" use="optional"/>	</xs:attributeGroup>	<xs:element name="config">		<xs:annotation>			<xs:documentation>root element aggregating all pool information there is.</xs:documentation>		</xs:annotation>		<xs:complexType>			<xs:sequence maxOccurs="unbounded">				<xs:element name="pool">					<xs:annotation>						<xs:documentation>Describes a single pool.</xs:documentation>					</xs:annotation>					<xs:complexType>						<xs:sequence>							<xs:element name="profile" minOccurs="0" maxOccurs="unbounded">								<xs:annotation>									<xs:documentation>Administrative profile defaults associated with a pool.</xs:documentation>								</xs:annotation>								<xs:complexType>									<xs:simpleContent>										<xs:extension base="xs:string">											<xs:attribute name="namespace" type="ProfileNamespace" use="required"/>											<xs:attribute name="key" type="xs:string" use="required"/>										</xs:extension>									</xs:simpleContent>								</xs:complexType>							</xs:element>							<xs:element name="lrc" maxOccurs="unbounded">								<xs:annotation>									<xs:documentation>Each pool may report to multiple LRCs.</xs:documentation>								</xs:annotation>								<xs:complexType>									<xs:attribute name="url" type="xs:anyURI" use="required"/>								</xs:complexType>							</xs:element>							<xs:element name="gridftp" maxOccurs="unbounded">								<xs:annotation>									<xs:documentation>Each pool may have multiple gridftp servers.</xs:documentation>								</xs:annotation>								<xs:complexType>									<xs:sequence>										<xs:element name="bandwidth" minOccurs="0" maxOccurs="unbounded">											<xs:annotation>												<xs:documentation>Stores the bandwidth informaion related to each gridftp server.</xs:documentation>											</xs:annotation>											<xs:complexType>												<xs:attribute name="dest-subnet" type="xs:string" use="required"/>												<xs:attribute name="avg-bandwidth" type="xs:float" use="required"/>												<xs:attribute name="max-bandwidth" type="xs:float" use="required"/>												<xs:attribute name="min-bandwidth" type="xs:float" use="required"/>												<xs:attribute name="avg-bandwidth-range1" type="xs:float" use="optional"/>												<xs:attribute name="avg-bandwidth-range2" type="xs:float" use="optional"/>												<xs:attribute name="avg-bandwidth-range3" type="xs:float" use="optional"/>												<xs:attribute name="avg-bandwidth-range4" type="xs:float" use="optional"/>											</xs:complexType>										</xs:element>									</xs:sequence>									<xs:attribute name="url" type="xs:anyURI" use="required">										<xs:annotation>											<xs:documentation>The URL (actually, it may be more a URI, but hey, so what) is the access URL to the gridftp server. Each pool may have multiple gridftp servers, or run multiple versions of Globus on different ports.</xs:documentation>										</xs:annotation>									</xs:attribute>									<xs:attribute name="storage" type="xs:string" use="optional" default="/">										<xs:annotation>											<xs:documentation>This element is the storage mount point prefix. Of course, this may get turned over into other things, augmented by user and system requirements etc. I believe that default works quite well for default Globus setups. </xs:documentation>										</xs:annotation>									</xs:attribute>									<xs:attributeGroup ref="GlobusVersionInfo"/>									<xs:attribute name="total-size" type="xs:decimal" use="optional"/>									<xs:attribute name="free-size" type="xs:decimal" use="optional"/>								</xs:complexType>							</xs:element>							<xs:element name="jobmanager" maxOccurs="unbounded">								<xs:annotation>									<xs:documentation>Each pool supports various (usually two) jobmanagers.</xs:documentation>								</xs:annotation>								<xs:complexType>									<xs:attribute name="universe" type="xs:token" use="required">										<xs:annotation>											<xs:documentation>The universe name is actually the primary key for the jobmanager identification.</xs:documentation>										</xs:annotation>									</xs:attribute>									<xs:attribute name="url" type="xs:string" use="required">										<xs:annotation>											<xs:documentation>The contact string is the secondary key for any job manager.</xs:documentation>										</xs:annotation>									</xs:attribute>									<xs:attributeGroup ref="GlobusVersionInfo">										<xs:annotation>											<xs:documentation>Any pool may have multiple versions of Globus installed, and these versions may have multiple jobmanagers listening on different ports.</xs:documentation>										</xs:annotation>									</xs:attributeGroup>									<xs:attribute name="free-mem" type="xs:string" use="optional"/>									<xs:attribute name="total-mem" type="xs:string" use="optional"/>									<xs:attribute name="max-count" type="xs:string" use="optional"/>									<xs:attribute name="max-cpu-time" type="xs:string" use="optional"/>									<xs:attribute name="running-jobs" type="xs:nonNegativeInteger" use="optional"/>									<xs:attribute name="jobs-in-queue" type="xs:nonNegativeInteger" use="optional"/>									<xs:attribute name="idle-nodes" type="xs:nonNegativeInteger" use="optional"/>									<xs:attribute name="total-nodes" type="xs:nonNegativeInteger" use="optional"/>									<xs:attribute name="os" type="xs:string" use="optional"/>									<xs:attribute name="arch" type="xs:string" use="optional"/>									<xs:attribute name="type" type="xs:string" use="optional"/>									<xs:attribute name="subnet" type="xs:string" use="optional"/>								</xs:complexType>							</xs:element>							<xs:element name="workdirectory" default="/tmp">								<xs:annotation>									<xs:documentation>Each pool may have one and only one work directory mount point.</xs:documentation>								</xs:annotation>								<xs:complexType>									<xs:simpleContent>										<xs:extension base="xs:string">											<xs:attribute name="total-size" type="xs:decimal" use="optional"/>											<xs:attribute name="free-size" type="xs:decimal" use="optional"/>										</xs:extension>									</xs:simpleContent>								</xs:complexType>							</xs:element>						</xs:sequence>						<xs:attribute name="handle" type="xs:ID" use="required"/>						<xs:attribute name="gridlaunch" type="xs:string" use="optional">							<xs:annotation>								<xs:documentation>This is the path to grid launch. As attributes are optional, each pool can have at most one grid launch path. More does not make sense, unless there are different launchers for different remote schedulers, and a pool supports more than two (fork + one other) remote schedulers. </xs:documentation>							</xs:annotation>						</xs:attribute>						<xs:attribute name="sysinfo" type="xs:string" use="optional" default="INTEL32::LINUX"/>					</xs:complexType>				</xs:element>			</xs:sequence>			<xs:attribute name="version" type="xs:decimal" use="optional" default="1.0"/>		</xs:complexType>	</xs:element></xs:schema>

=== QuarkNet-HEP/e-Labs/trunk/common/resources/classes/etc/sites-grid.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns="http://www.griphyn.org/chimera/GVDS-PoolConfig" 
xsi:schemaLocation="http://www.griphyn.org/chimera/GVDS  http://www.griphyn.org/chimera/gvds-poolcfg-1.5.xsd" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.5">


  <pool handle="teraport" sysinfo="INTEL32::LINUX">
    <gridftp url="gsiftp://tp-grid1.ci.uchicago.edu" storage="/home/hategan/scratch/i2u2" major="2" minor="2" patch="4"> 
    </gridftp>
    <jobmanager universe="vanilla" url="tp-grid1.ci.uchicago.edu/jobmanager-pbs" major="2" minor="2" patch="4" />
    <workdirectory>/home/hategan/scratch/i2u2</workdirectory>
    <profile namespace="GLOBUS" key="queue">fast</profile>
    <profile namespace="ENV" key="PATH">/bin:/usr/bin:/usr/local/bin:/home/hategan/i2u2/bin</profile>
  </pool>
  
  <pool handle="aux" sysinfo="INTEL32::LINUX">
    <gridftp  url="local://localhost" storage="/var/tmp" major="1" minor="0" patch="0" />
    <jobmanager universe="vanilla" url="local://localhost" major="1" minor="0" patch="0" />
    <workdirectory>/sandbox/quarkcat/tmp</workdirectory>
    <profile namespace="SWIFT" key="storagesize">40000000000</profile>
  </pool>
</config>

=== QuarkNet-HEP/e-Labs/template/resources/output/etc/sitesbk.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Generated Wed Aug 17 15:17:52 PDT 2005-->
<!--Generated by gmehta [US] -->
<config xmlns="http://www.griphyn.org/chimera/GVDS-PoolConfig" xsi:schemaLocation="http://www.griphyn.org/chimera/GVDS  http://www.griphyn.org/chimera/gvds-poolcfg-1.5.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.5">
  
	<pool handle="plussed" gridlaunch="/local/gridstart" sysinfo="INTEL32::LINUX">
		<lrc url="rls://dc-user.isi.edu"/>
		<gridftp  url="gsiftp://plussed.mcs.anl.gov:4021" storage="/sandbox/hategan/vds" major="2" minor="2" patch="4"> 
		</gridftp>
		<!--<jobmanager universe="vanilla" url="plussed.mcs.anl.gov:4022" major="4" minor="0" patch="2" />-->
		<jobmanager universe="vanilla" url="plussed.mcs.anl.gov:4020" major="2" minor="4" patch="2"/>
		<workdirectory >/homes/hategan/vdl2</workdirectory>
	</pool>
  
	<pool handle="localhost" sysinfo="INTEL32::LINUX">
		<gridftp url="local://localhost" storage="/home/mike/work/i2u2/tmp" major="1" minor="0" patch="0"/>
		<jobmanager universe="vanilla" url="local://localhost" major="1" minor="0" patch="0"/>
		<workdirectory>/home/mike/work/i2u2/tmp</workdirectory>
	</pool>
    
</config>

=== QuarkNet-HEP/e-Labs/common/resources/classes/etc/sites-mixed.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns="http://www.griphyn.org/chimera/GVDS-PoolConfig" 
xsi:schemaLocation="http://www.griphyn.org/chimera/GVDS  http://www.griphyn.org/chimera/gvds-poolcfg-1.5.xsd" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.5">


  <pool handle="localhost" sysinfo="INTEL32::LINUX">
    <gridftp  url="local://localhost" storage="/var/tmp" major="1" minor="0" patch="0" />
    <jobmanager universe="vanilla" url="local://localhost" major="1" minor="0" patch="0" />
    <workdirectory >/var/tmp</workdirectory>
    <profile namespace="SWIFT" key="storagesize">40000000000</profile>
  </pool>

  <pool handle="teraport" sysinfo="INTEL32::LINUX">
    <gridftp url="gsiftp://tp-grid1.uchicago.edu" storage="/home/hategan/scratch/i2u2" major="2" minor="2" patch="4"> 
    </gridftp>
    <jobmanager universe="vanilla" url="tp-grid1.uchicago.edu/jobmanager-pbs" major="2" minor="2" patch="4" />
    <workdirectory>/home/hategan/scratch/i2u2</workdirectory>
  </pool>
  
</config>
